# Localhost docker-compose for testing
# Create overrides for other environments
# https://docs.docker.com/compose/extends
version: '3.6'

services:
  server:
    build:
      context: server/.
    environment:
      - DB_HOST=host.docker.internal
    env_file:
      - server/.env
    ports:
      - 127.0.0.1:5000:5000
    restart: unless-stopped
  client:
    build:
      context: client/.
      args:
        VITE_API_URL: http://127.0.0.1:5000
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - server
    restart: unless-stopped
